// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nylznhahlamnynjrrfvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55bHpuaGFobGFtbnluanJyZnZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDg1MTgsImV4cCI6MjA2NjQyNDUxOH0.oQQNEgLGvBlQQO1R1AohQ-BOoWwm7mdD0ZC-Xeypemw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);